data <- read.table("household_power_consumption.txt",header=TRUE,sep=";")
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
data <- subset(data,(data$Date == "2007-02-01" | data$Date == "2007-02-02"))
data$Global_active_power <- as.character(data$Global_active_power)
data$Global_active_power <- as.numeric(data$Global_active_power)
data$DateTime <- paste(data$Date,data$Time)
data$DateTime <- strptime(data$DateTime,format = "%Y-%m-%d %H:%M:%S")
png(file = "plot2.png")
plot(data$DateTime,data$Global_active_power,type = "l",xlab = "",ylab = "Global Active Power (kilowatts)")
dev.off()

