data <- read.table("household_power_consumption.txt",header=TRUE,sep=";")
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
data <- subset(data,(data$Date == "2007-02-01" | data$Date == "2007-02-02"))
data$Global_active_power <- as.character(data$Global_active_power)
data$Global_active_power <- as.numeric(data$Global_active_power)
png(file = "plot1.png")
hist(data$Global_active_power,main = "Global Active Power",col = "Red",xlab = "Gloabl Active Power (kilowatts)")
dev.off()
